### ISSUE TITLE
Creating Safe: misplaced and unlinked privacy policy information

### ISSUE THREAD

**Issue by marcinbodnar** [near/ui.multisafe#110]
`By continuing you consent to the terms of use and privacy policy.` information on Creating Safe page is visible below the first input.

It should be placed at the bottom, and be linked to the Privacy Policy page.

**Comment by hcho112** [comment]
Do you know the link to Privacy Policy page? @marcinbodnar

**Comment by marcinbodnar** [comment]
> Do you know the link to Privacy Policy page? @marcinbodnar

@hcho112 I don't think we have one. I also added this PR #102 , so I think If we are not planning to add Privacy Policy soon, we should remove these two texts. cc @agileurbanite

**Comment by hcho112** [comment]
Since label shift has been completed, will close this issue
