### ISSUE TITLE
Bug: Removing empty members removes already defined members

### ISSUE THREAD

**Issue by agileurbanite** [near/ui.multisafe#115]
# Bug: Removing empty members removes already defined members

![2022-06-20 13 14 36](https://user-images.githubusercontent.com/2501324/174672281-b6daf3ba-fc7f-4d2d-9c49-b4773063fa58.gif)

**Comment by marcinbodnar** [comment]
It was fixed in:
https://github.com/near/ui.multisafe/pull/100
