### ISSUE TITLE
Feat: Update Menu for Transactions

### ISSUE THREAD

**Issue by agileurbanite** [near/ui.multisafe#129]
Update Menu for transactions:
![image](https://user-images.githubusercontent.com/2501324/176030538-3966e4bd-2de9-4ec4-b75c-89f768afcdf2.png)

The above should read:
* Transfer
* Custom Function

Transfer should support:

* Ability to transfer NEAR or FT (wNEAR)
* Ability to transfer NFT

**Comment by judith-Near** [comment]
addressed in this PR https://github.com/near/ui.multisafe/pull/133
