### ISSUE TITLE
Pending and Confirmed Requests Metadata

### ISSUE THREAD

**Issue by agileurbanite** [near/ui.multisafe#98]
On testnet, pending requests and completed requests need to show more metadata about the request and request type.  For example, in the below screenshot one of the requests is for adding an additional member to the safe and yet this is not evident in the UI.

Might need UX guidance.

![image](https://user-images.githubusercontent.com/2501324/174166383-c3a182ba-3190-4757-bbf6-c47f1a350f50.png)

**Comment by hcho112** [comment]
Resolved by [PR](https://github.com/near/ui.multisafe/pull/113)
